export default function () {
	return [
    {id: 1, cat: 'Haitian - Works Available', name: 'Aladin, Agathe', url: 'http://iartx.com/aladin-agathe.html'},
    {id: 2, cat: 'Haitian - Works Available', name: 'Armand, Gesner', url: 'http://iartx.com/armand-gesner.html'},
    {id: 3, cat: 'Haitian - Works Available', name: 'Auguste, Toussaint', url: 'http://iartx.com/auguste-toussaint.html'},
    {id: 4, cat: 'Haitian - Works Available', name: 'Bien-Aime, Gabriel', url: 'http://iartx.com/bien-aime-gabriel.html'},
    {id: 5, cat: 'Haitian - Works Available', name: 'Bigaud, Wilson', url: 'http://iartx.com/bigaud-wilson.html'},
    {id: 6, cat: 'Haitian - Works Available', name: 'Bottex, Seymour E.', url: 'http://iartx.com/bottex-s-e.html'},
    {id: 7, cat: 'Haitian - Works Available', name: 'Casimir, Laurent', url: 'http://iartx.com/casimir-laurent.html'},
    {id: 8, cat: 'Haitian - Works Available', name: 'Chéry, Jacques-Richard', url: 'http://iartx.com/chery-jacques-richard.html'},
    {id: 9, cat: 'Haitian - Works Available', name: 'Desrosiers, M.', url: 'http://iartx.com/desrosiers-m.html'},
    {id: 10, cat: 'Haitian - Works Available', name: 'Domond, Ezene', url: 'http://iartx.com/domond-ezene.html'},
    {id: 11, cat: 'Haitian - Works Available', name: 'Domond, Wilmino', url: 'http://iartx.com/domond-wilmino.html'},
    {id: 12, cat: 'Haitian - Works Available', name: 'Dreux, Nicolas', url: 'http://iartx.com/dreux-nicolas.html'},
    {id: 13, cat: 'Haitian - Works Available', name: 'Francois, Roger', url: 'http://iartx.com/francois-roger.html'},
    {id: 14, cat: 'Haitian - Works Available', name: 'Hector, Voltaire', url: 'http://iartx.com/hector-voltaire.html'},
    {id: 15, cat: 'Haitian - Works Available', name: 'Jean, Ulrick M.', url: 'http://iartx.com/jean-ulrick.html'},
    {id: 16, cat: 'Haitian - Works Available', name: 'Jean-Jacques, Carlo', url: 'http://iartx.com/jean-jacques-carlo.html'},
    {id: 17, cat: 'Haitian - Works Available', name: 'Jose, Hilome', url: 'http://iartx.com/jose-hilome.html'},
    {id: 18, cat: 'Haitian - Works Available', name: 'Joseph, Reynald', url: 'http://iartx.com/joseph-reynald.html'},
    {id: 19, cat: 'Haitian - Works Available', name: 'Louis, Wilfrid', url: 'http://iartx.com/louis-wilfrid.html'},
    {id: 20, cat: 'Haitian - Works Available', name: 'Maurice, A.M.', url: 'http://iartx.com/maurice-a-m.html'},
    {id: 21, cat: 'Haitian - Works Available', name: 'Obin, Philomé', url: 'http://iartx.com/obin-philome.html'},
    {id: 22, cat: 'Haitian - Works Available', name: 'Pierre, André', url: 'http://iartx.com/pierre-andre.html'},
    {id: 23, cat: 'Haitian - Works Available', name: 'Profil, Jonas', url: 'http://iartx.com/profil-jonas.html'},
    {id: 24, cat: 'Haitian - Works Available', name: 'St. Fleur, Michelle', url: 'http://iartx.com/st-fleur-michelle.html'},
    {id: 25, cat: 'Haitian - Works Available', name: 'Stephane, Micius', url: 'http://iartx.com/stephane-micius.html'},
    {id: 26, cat: 'Haitian - Works Available', name: 'Zephirin, Frantz', url: 'http://iartx.com/zephirin-frantz.html'},
    {id: 27, cat: 'Haitian - Sales Archives', name: 'Aladin, Theard', url: 'http://iartx.com/aladin-theard.html'},
    {id: 28, cat: 'Haitian - Sales Archives', name: 'Alphonse, Fritzner', url: 'http://iartx.com/alphonse-fritzner.html'},
    {id: 29, cat: 'Haitian - Sales Archives', name: 'Dupoux, Raoul', url: 'http://iartx.com/dupoux-raoul.html'},
    {id: 30, cat: 'Haitian - Sales Archives', name: 'Etienne, Gregoire', url: 'http://iartx.com/etienne-gregoire.html'},
    {id: 31, cat: 'Haitian - Sales Archives', name: 'Guillaume, Jean-Jacques', url: 'http://iartx.com/guillaume-jean-jacques.html'},
    {id: 32, cat: 'Haitian - Sales Archives', name: 'Ismael, Saincilus', url: 'http://iartx.com/ismael-saincilus.html'},
    {id: 33, cat: 'Haitian - Sales Archives', name: 'Jacques, Harry', url: 'http://iartx.com/jacques-harry.html'},
    {id: 34, cat: 'Haitian - Sales Archives', name: 'Jean, Jean-Baptiste', url: 'http://iartx.com/jean-jean-baptiste.html'},
    {id: 35, cat: 'Haitian - Sales Archives', name: 'Jean, Marie Carmel', url: 'http://iartx.com/jean-marie-carmel.html'},
    {id: 36, cat: 'Haitian - Sales Archives', name: 'Joseph, Jasmin', url: 'http://iartx.com/joseph-jasmin.html'},
    {id: 37, cat: 'Haitian - Sales Archives', name: 'Louissaint, Jacques', url: 'http://iartx.com/louissaint-jacques.html'},
    {id: 38, cat: 'Haitian - Sales Archives', name: 'Louizor, Ernst', url: 'http://iartx.com/louizor-ernst.html'},
    {id: 39, cat: 'Haitian - Sales Archives', name: 'Martinez, Florence', url: 'http://iartx.com/martinez-florence.html'},
    {id: 40, cat: 'Haitian - Sales Archives', name: 'Obin, Fritzner', url: 'http://iartx.com/obin-fritzner.html'},
    {id: 41, cat: 'Haitian - Sales Archives', name: 'Obin, Othon', url: 'http://iartx.com/obin-othon.html'},
    {id: 42, cat: 'Haitian - Sales Archives', name: 'Pierre, Eddy', url: 'http://iartx.com/pierre-eddy.html'},
    {id: 43, cat: 'Haitian - Sales Archives', name: 'Rameau, Cameau', url: 'http://iartx.com/rameau-cameau.html'},
    {id: 44, cat: 'Haitian - Sales Archives', name: 'Robuste, Jean Claude', url: 'http://iartx.com/robuste-jean-claude.html'},
    {id: 45, cat: 'Haitian - Sales Archives', name: 'Valcin, Pierre Joseph', url: 'http://iartx.com/valcin-pierre-joseph.html'},
    {id: 46, cat: 'Haitian - Sales Archives', name: 'Valery, Julien', url: 'http://iartx.com/valery-julien.html'},
    {id: 47, cat: 'Haitian - Sales Archives', name: 'Zephirin Jr, Frantz "Frantzy"', url: 'http://iartx.com/zephirin-jr-frantzy.html'},
    {id: 48, cat: 'Artists from Other Countries', name: 'Benjamin, John (Grenada)', url: 'http://iartx.com/benjamin-john.html'},
    {id: 49, cat: 'Artists from Other Countries', name: 'Cato, Elinus (Grenada)', url: 'http://iartx.com/cato-elinus.html'},
    {id: 50, cat: 'Artists from Other Countries', name: 'Dodson, Ann (Barbados)', url: 'http://iartx.com/dodson-ann.html'},
    {id: 51, cat: 'Artists from Other Countries', name: 'Emhardt, Erna (Germany)', url: 'http://iartx.com/emhardt-erna.html'},
    {id: 52, cat: 'Artists from Other Countries', name: 'Jančić, Đuro (Croatia)', url: 'http://iartx.com/jancic-duro.html'},
    {id: 53, cat: 'Artists from Other Countries', name: 'Khanh, Kao Van (Vietnam)', url: 'http://iartx.com/khanh-kao-van.html'},
    {id: 54, cat: 'Artists from Other Countries', name: 'Kuhlman, Walter (USA)', url: 'http://iartx.com/kuhlman-walter.html'},
    {id: 55, cat: 'Artists from Other Countries', name: 'Resimcioğlu, Mehmet Ali (Turkey)', url: 'http://iartx.com/mehmet.html'},
    {id: 56, cat: 'Artists from Other Countries', name: 'Rodríguez, María Dolores (Puerto Rico)', url: 'http://iartx.com/rodriguez-maria-dolores.html'},
    {id: 57, cat: 'Artists from Other Countries', name: 'Taylor, J. (Jamaica)', url: 'http://iartx.com/taylor-j.html'},
    {id: 58, cat: 'Artists from Other Countries', name: 'Thomas, Kingsley (Jamaica)', url: 'http://iartx.com/thomas-kingsley.html'}
 ]
}
